base_path: ../../datasets/
result_path: ../results/
data_name: nus
model_name: vgg19
batch_size: 64
bit: 64
learning_rate: 0.005
momentum: 0.9
weight_decay: 0.0005
epoch_num: 100

label_path: mini_nus-tc10-lall.mat
text_path: mini_nus-tc10-yall.mat
image_path: mini_nus-tc10-iall.mat

distance_weight: 0.01
possibility_weight: 0.3
possibility_scale: 4000

dw: 1
cw: 1
K: 1.5
KNN: 3000
top_hamming: 5
eval_interval: 1
eval_epoch: 0

# 使用Sgc来指导正负样本的区分的阈值：
# > PP_threshold ： PP， 正样本
# < NP_threshold : NP, 负样本
PP_threshold: 0.8
NP_threshold: 0.4

temperature: 0.7
infoNCE_weight: 1.0

# build multi KNN
KNN_layers: 3
KNN_base: 3000
KNN_gap:  1000
KNN_weight_base: 0.5
KNN_weight_gap: -0.1