base_path: ../../datasets/
result_file_path: ../results/best_result.txt
data_name: flickr
model_name: vgg19
batch_size: 64
bit: 128
learning_rate: 0.005
momentum: 0.9
weight_decay: 0.0005
epoch_num: 100

label_path: mini_nus-tc10-lall.mat
text_path: mini_nus-tc10-yall.mat
image_path: mini_nus-tc10-iall.mat

distance_weight: 0.01
possibility_weight: 0.3
possibility_scale: 4000

dw: 1
cw: 1
K: 1.5
top_hamming: 5
KNN: 3000

# build multi KNN
KNN_layers: 3
KNN_base: 3000
KNN_gap: 1000
KNN_weight_base: 0.6
KNN_weight_gap: 0.1
